// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;
import java.util.concurrent.TimeUnit;

public class App {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","/home/beckhamochieng/EssayShark/EssayShark/src/chromedriver");
    // System.setProperty("webdriver.chrome.driver","/home/azureuser/EssayShark/src/chromedriver");

    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless");
    driver = new ChromeDriver(options);

    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test()
  public void app() {

    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(300000000));
    
    driver.get("https://essayshark.com/");
    // 2 | setWindowSize | 1920x1003 | 
    driver.manage().window().setSize(new Dimension(1920, 1003));
    
    /*
     * LOGGING ITNO THE WEBSITE
     */
    driver.findElement(By.cssSelector(".bb-accountEmptyButton")).click();
    // 4 | click | css=.bb-authFields .bb-loginField > .bb-input | 
    driver.findElement(By.cssSelector(".bb-authFields .bb-loginField > .bb-input")).click();
    // 5 | mouseDownAt | name=password | 167.5,-0.5
    {
      WebElement element = driver.findElement(By.name("password"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    // 6 | mouseMoveAt | name=password | 167.5,-0.5
    {
      WebElement element = driver.findElement(By.name("password"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 7 | mouseUpAt | name=password | 167.5,-0.5
    {
      WebElement element = driver.findElement(By.name("password"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    // 8 | click | css=.bb-authFields | 
    driver.findElement(By.cssSelector(".bb-authFields")).click();
    // 9 | type | css=.bb-authFields .bb-loginField > .bb-input | Glule83x@gmail.com
    driver.findElement(By.cssSelector(".bb-authFields .bb-loginField > .bb-input")).sendKeys("");
    // 10 | click | name=password | 
    driver.findElement(By.name("password")).click();
    // 11 | type | name=password | Lexz2023
    driver.findElement(By.name("password")).sendKeys("");
    // Clixk login button
    // driver.manage().timeouts().implicitlyWait(10,TimeUnit.SECONDS) ;
    // Enter
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    /*
     * OPENING TASK TABE AND DOING THEM
    */

 while (true)  {
    wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html/body/div[2]/div/div[5]/div/div[2]/table/tbody/tr[9]/td[2]/a")));

    driver.findElement(By.xpath("/html/body/div[2]/div/div[5]/div/div[2]/table/tbody/tr[9]/td[2]/a")).click();

    try {

        while (true) {
            driver.navigate().refresh();
            driver.findElement(By.id("rec_bid")).click();
            driver.findElement(By.id("apply_order")).click();
        }

      } catch (Exception e) {
        driver.findElement(By.xpath("//*[@id='user_nav']/li[1]/a")).click();
    }
    
}
}
}
